[package]
name = "v4vmm"
version = "0.1.0"
edition = "2021"

[dependencies]
toml  = "1.0"
id3 = "1"
rusqlite = { version = "0.38", features = ["bundled"] }
reqwest = { version = "0.13", features = ["blocking"] }
rss = "2"
chrono = { version = "0.4", default-features = false, features = ["std"] }

# config parsing
serde = { version = "1", features = ["derive"] }
directories = "6" 

# nice error handling
anyhow = "1"